"""change fk name

Revision ID: bea4e0dc7588
Revises: f0d6c5d5cca3
Create Date: 2025-12-04 11:35:23.847538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bea4e0dc7588"
down_revision: Union[str, Sequence[str], None] = "f0d6c5d5cca3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key("new_user_task_id", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_constraint("new_user_task_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
